### ISSUE TITLE
Oculus Client Error

### ISSUE THREAD

**Issue by Cellguy16** [Tech-How/Oculus-Offline-Installer#2]
I'm having a problem where the Oculus software would install fine using the official installer, but using the scripts to install it results in an error. This error log is an Oculus Client error log, located in C:\Users\username\AppData\Roaming\Oculus\.

> Server closed connection
Browser process crashed with exception: Error: Cannot find module '../screen'
Error: Cannot find module '../screen'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (C:\Program Files\Oculus\Support\oculus-client\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.get [as screen] (C:\Program Files\Oculus\Support\oculus-client\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at i (C:\Program Files\Oculus\Support\oculus-client\resources\app.asar\output\app.js:6:118992)
    at Object.assign (C:\Program Files\Oculus\Support\oculus-client\resources\app.asar\output\app.js:14:113644)
    at new t.default (C:\Program Files\Oculus\Support\oculus-client\resources\app.asar\output\app.js:14:113817)
    at t.default.openSplashWindow (C:\Program Files\Oculus\Support\oculus-client\resources\app.asar\output\app.js:14:22119)

**Comment by Cellguy16** [comment]
I successfully fixed the problem by temporarily changing the date and time back to 2017 when launching the Oculus Client. It had something to do with the verification of a DLL file.
